---
- name: Copy spring boot app to application server
  copy:
    src: /home/gvakhariya/easy-notes-1.0.0.jar
    dest: /home/gvakhariya/spring_boot_apps/

- name: Set mysql coonection url as environment variable
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: '^MYSQL_CONNECTION_URL'
    line: 'MYSQL_CONNECTION_URL=jdbc:mysql://10.128.0.4:3306/notes_app?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false'


- name: Set mysql username as environment variable
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: '^MYSQL_DB_USERNAME'
    line: 'MYSQL_DB_USERNAME=root'    

- name: Set mysql password as environment variable
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: '^MYSQL_DB_PASSWORD'
    line: 'MYSQL_DB_PASSWORD=root'

 
- name: Starting Application on1 port 8081
  shell: java -Dserver.port=8081 -jar /home/gvakhariya/spring_boot_apps/easy-notes-1.0.0.jar

- name: Starting Application on port 8082
  shell: java -Dserver.port=8082 -jar /home/gvakhariya/spring_boot_apps/easy-notes-1.0.0.jar 
